# Setup
title:               '#Feng'
tagline:             'Tech Blog'
description:         'Hi peeps'
url:                 #
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Feng Sifang
  url:               #
  email:             #

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
